### ISSUE TITLE
Lack of documentation to set-up clearing house

### ISSUE THREAD

**Issue by jfernandezsqs** [Fraunhofer-AISEC/ids-clearing-house-core#1]
I have reviewed the latest Clearing House documentation update of the README.md

It does not specify or detail how this component should be launched together with the trusted connector. In addition, the trusted connector documentation in the README.md details that there are failures in the component build. [https://industrial-data-space.github.io/trusted-connector-documentation/docs/dev_core/#build ]
![image](https://user-images.githubusercontent.com/82888094/139254423-22da3af4-37fb-4c3b-8e27-c99708054e36.png)
I have tried with version 4.0.0, with 5.0.0, with 5.0.2 and with the master, but none of them gives a satisfactory result when launching the command of the documentation -->  ./build.sh 
The documentation for launching the Trusted Connector is not adequate and cannot be followed due to failures that occur in the building of the core platform. 
![image](https://user-images.githubusercontent.com/82888094/139254560-5f675f43-04e4-45c1-9265-ee54a2d4bd84.png)

Could you please detail how to deploy the clearing house?
Could you indicate how you have achieved a deployment of clearing house and trusted connector? 
Thanks in advance,

**Comment by kragall** [comment]
I've never built the trusted connector myself, so I can't help you with figuring out why it fails. I use the docker image `fraunhoferaisec/trusted-connector-core:5.0.2` from docker hub to run the trusted connector.

The docker images for the Clearing House can be build using the files located in the docker directories of [core](https://github.com/Fraunhofer-AISEC/ids-clearing-house-core/tree/master/docker) and [service](https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/tree/master/docker).

**Comment by jfernandezsqs** [comment]
I have the docker image of the trusted connector version 5.0.2 
Looking at the documentation of the clearing house and going to the folders that you indicate to mount the images. I am not able to deploy the Clearing House with the trusted connector. 
There is a lack of documentation for the correct installation of the Clearing House, there are no steps to follow in order to set-up core and service.
Could you specify in the documentation the steps and commands needed for a correct set-up?
Thanks in advance,

**Comment by kragall** [comment]
Documentation has been updated and should contain everything needed for a correct set-up
